// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
config({ path: ".env.local" });
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["RAG_WRITE_DATABASE_URL"] ?? process.env["RAG_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
